apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  labels:
    app: movie-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: movie-app-kube
        imagePullPolicy: Never
        env: 
          - name: DBURI
            value: mongodb://movie-mongo-service/moviedb
          - name: PORT
            value: "4000"
        ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
  labels:
    run: movie-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app: movie-app