apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-mongo-pv-claim
  labels:
    app: movie-mongo
spec:
  accessModes:
    - ReadWriteOnce #only one node can mount in read write mode
  resources:
    requests:
      storage: 1Gi #1 GB

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: movie-mongo
  labels:
    app: movie-mongo
spec:
  selector: 
    matchLabels:
      app: movie-mongo
  template:
    metadata:
      labels:
        app: movie-mongo
    spec:
      containers:
        - image: mongo:4.0 
          name: movie-mongo
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-pv-storage
              mountPath: /data/db
      volumes:
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: movie-mongo-pv-claim


---

apiVersion: v1
kind: Service
metadata:
  name: movie-mongo-service
  labels:
    app: movie-mongo
spec:
  ports:
    - port: 27017
  selector:
    app: movie-mongo